// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABuKbcmp2zgnBXxh3GTo6QFUFDyiCt0II',
    appId: '1:490561408004:web:2d12611385c996a25a3951',
    messagingSenderId: '490561408004',
    projectId: 'careerpath-849d0',
    authDomain: 'careerpath-849d0.firebaseapp.com',
    storageBucket: 'careerpath-849d0.firebasestorage.app',
    measurementId: 'G-0TBMZELN3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrb4oQGLFZn-Zd_hUsuVRL9fV-0Ls_Qco',
    appId: '1:490561408004:android:18dfb213f7e8516c5a3951',
    messagingSenderId: '490561408004',
    projectId: 'careerpath-849d0',
    storageBucket: 'careerpath-849d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3DQ7QiydotttDs-GpKe5N7xAZ0QmIAXI',
    appId: '1:490561408004:ios:7b10852211f67da55a3951',
    messagingSenderId: '490561408004',
    projectId: 'careerpath-849d0',
    storageBucket: 'careerpath-849d0.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3DQ7QiydotttDs-GpKe5N7xAZ0QmIAXI',
    appId: '1:490561408004:ios:7b10852211f67da55a3951',
    messagingSenderId: '490561408004',
    projectId: 'careerpath-849d0',
    storageBucket: 'careerpath-849d0.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABuKbcmp2zgnBXxh3GTo6QFUFDyiCt0II',
    appId: '1:490561408004:web:79d289c972b3581e5a3951',
    messagingSenderId: '490561408004',
    projectId: 'careerpath-849d0',
    authDomain: 'careerpath-849d0.firebaseapp.com',
    storageBucket: 'careerpath-849d0.firebasestorage.app',
    measurementId: 'G-EVP7VBHEMB',
  );
}
